### ISSUE TITLE
Error :  getMaterialColors

### ISSUE THREAD

**Issue by juamor86** [LukeDeighton/WheelView#31]
Caused by: java.lang.IllegalArgumentException: Not a primitive field: com.android.tools.fd.runtime.IncrementalChange com.lukedeighton.wheelsample.R$color.$change
                                                                                  at java.lang.reflect.Field.getInt(Native Method)
                                                                                  at java.lang.reflect.Field.getInt(Field.java:460)
                                                                                  at com.lukedeighton.wheelsample.MaterialColor.getMaterialColors(MaterialColor.java:27)

**Comment by ChaosLeong** [comment]
`com.android.tools.fd.runtime.IncrementalChange` was added to support [instant run](http://tools.android.com/tech-docs/instant-run). 
Disable instant run can solve the problem.
or 
add the following code before [field.getInt(null)](https://github.com/LukeDeighton/WheelView/blob/master/WheelViewSample%2Fsrc%2Fmain%2Fjava%2Fcom%2Flukedeighton%2Fwheelsample%2FMaterialColor.java#L27)
``` java
if (field.getType() != int.class) continue;
```

**Comment by LukeDeighton** [comment]
thanks @ChaosLeong
