### ISSUE TITLE
Error run example app

### ISSUE THREAD

**Issue by diogoico** [LukeDeighton/WheelView#33]
As soon as I run the example the app crashes with the msg, any ideas?:

> 04-22 11:14:33.480 17741-17741/com.lukedeighton.wheelsample E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                               java.lang.ClassCastException: com.lukedeighton.wheelsample.MainActivity$1 cannot be cast to com.lukedeighton.wheelsample.MainActivity$MaterialColorAdapter
>                                                                                   at com.lukedeighton.wheelsample.MainActivity$2.onWheelItemSelected(MainActivity.java:62)
>                                                                                   at com.lukedeighton.wheelview.WheelView.setSelectedPosition(WheelView.java:951)
>                                                                                   at com.lukedeighton.wheelview.WheelView.updateSelectedPosition(WheelView.java:932)
>                                                                                   at com.lukedeighton.wheelview.WheelView.setAngle(WheelView.java:918)
>                                                                                   at com.lukedeighton.wheelview.WheelView.addAngle(WheelView.java:1020)
>                                                                                   at com.lukedeighton.wheelview.WheelView.onTouchEvent(WheelView.java:1075)
>                                                                                   at android.view.View.dispatchTouchEvent(View.java:7246)
>                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
>                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
>                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
>                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
>                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
>                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
>                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2174)
>                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1953)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
>                                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2410)
>                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1901)
>                                                                                   at android.view.View.dispatchPointerEvent(View.java:7426)
>                                                                                   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3240)
>                                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3184)
>                                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4341)
>                                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4320)
>                                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4412)
>                                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
>                                                                                   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
>                                                                                   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
>                                                                                   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4391)
>                                                                                   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4431)
>                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
>                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:562)
>                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:530)
>                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
>                                                                                   at android.os.Handler.handleCallback(Handler.java:725)
>                                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
>                                                                                   at android.os.Looper.loop(Looper.java:137)
>                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5041)
>                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
>                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
>                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
>                                                                                   at dalvik.system.NativeStart.main(Native Method)
> 04-22 11:14:33.510 17741-17743/com.lukedeighton.wheelsample D/dalvikvm: GC_CONCURRENT freed 273K, 19% free 4229K/5200K, paused 2ms+1ms, total 20ms
> 04-22 11:14:43.610 17741-17772/com.lukedeighton.wheelsample E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.android.tools.fd.runtime.Restarter.getActivities
> 04-22 11:14:43.610 17741-17772/com.lukedeighton.wheelsample W/dalvikvm: VFY: unable to resolve instanceof 1787 (Landroid/util/ArrayMap;) in Lcom/android/tools/fd/runtime/Restarter;
> 04-22 11:14:43.610 17741-17772/com.lukedeighton.wheelsample D/dalvikvm: VFY: replacing opcode 0x20 at 0x0071
>

**Comment by LukeDeighton** [comment]
@diogoico the stack trace looks strange if this happens as soon as you start up the app as it looks like it's failing on a touch event. I have just fixed an issue that caused it to crash so maybe pull the latest and try again?
