### ISSUE TITLE
Not Run in Android Studio 2.1

### ISSUE THREAD

**Issue by pinakgauswami** [LukeDeighton/WheelView#34]
FATAL EXCEPTION: main
Process: com.lukedeighton.wheelsample, PID: 3692
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lukedeighton.wheelsample/com.lukedeighton.wheelsample.MainActivity}: java.lang.IllegalArgumentException: Not a primitive field: com.android.tools.fd.runtime.IncrementalChange com.lukedeighton.wheelsample.R$color.$change
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2303)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5234)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
                                                                             Caused by: java.lang.IllegalArgumentException: Not a primitive field: com.android.tools.fd.runtime.IncrementalChange com.lukedeighton.wheelsample.R$color.$change
                                                                                at java.lang.reflect.Field.getInt(Native Method)
                                                                                at java.lang.reflect.Field.getInt(Field.java:460)
                                                                                at com.lukedeighton.wheelsample.MaterialColor.getMaterialColors(MaterialColor.java:27)
                                                                                at com.lukedeighton.wheelsample.MaterialColor.random(MaterialColor.java:39)
                                                                                at com.lukedeighton.wheelsample.MainActivity.onCreate(MainActivity.java:34)
                                                                                at android.app.Activity.performCreate(Activity.java:5982)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2256)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5234) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by LukeDeighton** [comment]
@pinakgauswami - this has been fixed just now
