### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.recycle()' on a null object reference

### ISSUE THREAD

**Issue by AlexandroKurchenko** [LukeDeighton/WheelView#39]
The issue comes when i  make swipe to close the wheel activity. I am reproduce it on Moto 360 1st generation. Have a next log:
` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.bla.bla PID: 21940
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.recycle()' on a null object reference
                                                                    at com.lukedeighton.wheelview.WheelView.onTouchEvent(WheelView.java:931)
                                                                    at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                    at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4239)
                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4105)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3796)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3853)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5933)
                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5907)
                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5868)
                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6036)
                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6007)
                                                                    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6059)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:600)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by LukeDeighton** [comment]
Try using my library version `0.4.1` I should hopefully prevent that null pointer from happening

**Comment by AlexandroKurchenko** [comment]
Seams to be fixed now. Thanks you very much.
